# Generated by Django 5.0.6 on 2024-07-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saler_reg',
        ),
    ]
