# Generated by Django 5.0.6 on 2024-07-08 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0005_saler_reg'),
        ('myadmin', '0002_categories_subcategories'),
        ('saler', '0002_delete_saler_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('details', models.TextField()),
                ('quantity', models.BigIntegerField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.categories')),
                ('saler_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.saler_reg')),
                ('subcategories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.subcategories')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
