# Generated by Django 5.0.6 on 2024-07-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=255),
        ),
    ]
