# Generated by Django 5.0.6 on 2024-07-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_saler_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Saler_reg',
        ),
    ]
