# Generated by Django 5.0.6 on 2024-07-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_saler_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='saler_reg',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
